// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARaohXnhH5F0SHcVyomCkHzwrxc9ddVms',
    appId: '1:436303813301:web:24d07a7491cffed3ab7cfc',
    messagingSenderId: '436303813301',
    projectId: 'erguo-application-9ccb4',
    authDomain: 'erguo-application-9ccb4.firebaseapp.com',
    storageBucket: 'erguo-application-9ccb4.firebasestorage.app',
    measurementId: 'G-CZLWS8WTJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXwEdETmddpQzmHdOMkMPNhdyArfi6kuM',
    appId: '1:436303813301:android:7eda937715e42704ab7cfc',
    messagingSenderId: '436303813301',
    projectId: 'erguo-application-9ccb4',
    storageBucket: 'erguo-application-9ccb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJjLHps7qAUpPUupAwIhVNC842x3is3ZU',
    appId: '1:436303813301:ios:ee3453e67d389150ab7cfc',
    messagingSenderId: '436303813301',
    projectId: 'erguo-application-9ccb4',
    storageBucket: 'erguo-application-9ccb4.firebasestorage.app',
    iosBundleId: 'com.example.erguo',
  );

}