// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4GPKtuK2YxIjyamQeyRxuY-LrSRoSr38',
    appId: '1:899177907952:web:a102964267db805c44a435',
    messagingSenderId: '899177907952',
    projectId: 'erguo-application',
    authDomain: 'erguo-application.firebaseapp.com',
    storageBucket: 'erguo-application.firebasestorage.app',
    measurementId: 'G-WN9S7KK7FN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJpK4DL2L-q7QVwigi2NqkBxdNIkJgLHc',
    appId: '1:899177907952:android:d7e5f029ad53f4be44a435',
    messagingSenderId: '899177907952',
    projectId: 'erguo-application',
    storageBucket: 'erguo-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCYEIVGWI7wZHn8AjvBBiFu_0kz_wsGZg',
    appId: '1:899177907952:ios:6e6b58c0c16e4e4e44a435',
    messagingSenderId: '899177907952',
    projectId: 'erguo-application',
    storageBucket: 'erguo-application.firebasestorage.app',
    iosBundleId: 'com.example.erguo',
  );
}
